name: Publish Snapshot to Github Packages
on:
  release:
    types: [created, published, edited]
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo name with owner'
        required: true
        default: 'grepr/flink-ml'
      ref:
        description: 'The branch name'
        required: true
jobs:
  publish:
    if: github.repository == 'grepr/flink-ml'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: snapshot-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            snapshot-maven-

      - name: Publish snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(git rev-parse --short HEAD)
          mvn -B versions:set -DnewVersion=grepr-${VERSION} -DgenerateBackupPoms=false
          
          tmp_settings="tmp-settings.xml"
          echo "<settings><servers><server>" > $tmp_settings
          echo "<id>github</id><username>${GITHUB_ACTOR}</username>" >> $tmp_settings
          echo "<password>${GITHUB_TOKEN}</password>" >> $tmp_settings
          echo "</server></servers></settings>" >> $tmp_settings
          
          mvn -B --settings $tmp_settings clean deploy \
          -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/grepr/flink-ml \
          -pl flink-ml-iteration-2.2 -am -DskipTests -Dspotless.check.skip=true
          
          rm $tmp_settings